//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Messages.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات با خطا مواجه شد..
        /// </summary>
        public static string ActionsHasError {
            get {
                return ResourceManager.GetString("ActionsHasError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان حذف این {0} وجود ندارد!.
        /// </summary>
        public static string CanNotDelete {
            get {
                return ResourceManager.GetString("CanNotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره تلفن همراه قبلا تایید شده است!.
        /// </summary>
        public static string CellPhoneNumberAlreadyVerified {
            get {
                return ResourceManager.GetString("CellPhoneNumberAlreadyVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تکرار کلمه عبور با کلمه عبور وارد شده یکسان نیست..
        /// </summary>
        public static string ComparePasswordIsInValid {
            get {
                return ResourceManager.GetString("ComparePasswordIsInValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات با خطا مواجه شد. جزئیات: {0}.
        /// </summary>
        public static string DefaultExceptionError {
            get {
                return ResourceManager.GetString("DefaultExceptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  کاربر گرامی ایمیل شما تکراری میباشد..
        /// </summary>
        public static string EmailAddressAlreadyExsist {
            get {
                return ResourceManager.GetString("EmailAddressAlreadyExsist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نشانی پست الکترونیکی قبلا تایید شده است!.
        /// </summary>
        public static string EmailAddressAlreadyVerified {
            get {
                return ResourceManager.GetString("EmailAddressAlreadyVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نشانی پست الکترونیکی شما تایید نشده است!.
        /// </summary>
        public static string EmailAddressNotVerified {
            get {
                return ResourceManager.GetString("EmailAddressNotVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات ارسال ایمیل بازیابی با خطا مواجه شد. لطفا با پشتیبانی تماس بگیرید.
        /// </summary>
        public static string ErrorSendEmailResetPassword {
            get {
                return ResourceManager.GetString("ErrorSendEmailResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات ارسال ایمیل فعالسازی با خطا مواجه شد. لطفا با پشتیبانی تماس بگیرید.
        /// </summary>
        public static string ErrorSendEmailVerification {
            get {
                return ResourceManager.GetString("ErrorSendEmailVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد فعال‌سازی صحیح نمی‌باشد!.
        /// </summary>
        public static string InvalidVerificationKey {
            get {
                return ResourceManager.GetString("InvalidVerificationKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات با خطا مواجه شد. جزئیات: خطای اعتبار سنجی فرم رخ داده است؛ لطفا فرم را بررسی کنید.
        /// </summary>
        public static string ModelStateIsNotValid {
            get {
                return ResourceManager.GetString("ModelStateIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست شما غیر مجاز است. لطفا فرم ارسالی را بررسی و دوباره ارسال نمائید..
        /// </summary>
        public static string ModelStateIsNotValidForm {
            get {
                return ResourceManager.GetString("ModelStateIsNotValidForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متأسفیم که نتوانستید وارد شوید. لطفاً با مالک این سایت تماس بگیرید و مستقیماً برای دسترسی با آنها تماس بگیرید..
        /// </summary>
        public static string ModelStateIsNotValidForm1 {
            get {
                return ResourceManager.GetString("ModelStateIsNotValidForm1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای ثبت سفارش باید روش پرداخت را انتخاب کنید.
        /// </summary>
        public static string NotSelectingPaymentMethod {
            get {
                return ResourceManager.GetString("NotSelectingPaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطای ارتباط با سرور رخ داده است. در صورت کسر وجه با فروشگاه تماس حاصل فرمائید. کد پیگیری:  {0}.
        /// </summary>
        public static string PaymentExceptionError {
            get {
                return ResourceManager.GetString("PaymentExceptionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پرداخت ناموفق بود.
        /// </summary>
        public static string PaymentFailedError {
            get {
                return ResourceManager.GetString("PaymentFailedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطای ارتباط با سرور درگاه پرداخت.
        /// </summary>
        public static string PaymentGatewayServer {
            get {
                return ResourceManager.GetString("PaymentGatewayServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  کاربر گرامی شماره همراه شما تکراری میباشد..
        /// </summary>
        public static string PhoneNumberAlreadyExsist {
            get {
                return ResourceManager.GetString("PhoneNumberAlreadyExsist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره تلفن همراه شما تایید نشده است..
        /// </summary>
        public static string PhoneNumberNotVerified {
            get {
                return ResourceManager.GetString("PhoneNumberNotVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسیر یکتا تکراری است!.
        /// </summary>
        public static string RouteDuplicate {
            get {
                return ResourceManager.GetString("RouteDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطای ورود به سیستم! شماره تلفن همراه یا کلمه عبور را اشتباه وارد کرده باشید..
        /// </summary>
        public static string SignInError {
            get {
                return ResourceManager.GetString("SignInError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطای ناشناخته‌ای صورت گرفته است! لطفا با تیم پشتیبانی تماس حاصل فرمایید..
        /// </summary>
        public static string UnexpectedError {
            get {
                return ResourceManager.GetString("UnexpectedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطا در جایگزینی فایل. احتمال دارد فایل در حال استفاده باشد یا مجوز دسترسی در سرور صادر نشده باشد..
        /// </summary>
        public static string UnexpectedFileUploadError {
            get {
                return ResourceManager.GetString("UnexpectedFileUploadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موجودی کیف پول شما برای پرداخت این سفارش کافی نیست. لطفا کیف پول خود را شارژ کنید.
        /// </summary>
        public static string UserWalletInventoryIsNotEnougth {
            get {
                return ResourceManager.GetString("UserWalletInventoryIsNotEnougth", resourceCulture);
            }
        }
    }
}
