//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Messages.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متأسفیم که نتوانستید وارد شوید. لطفاً با مالک این سایت تماس بگیرید و مستقیماً برای دسترسی با آنها تماس بگیرید..
        /// </summary>
        internal static string AccessDeniedPageMessage {
            get {
                return ResourceManager.GetString("AccessDeniedPageMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یک خدمت با نام {0} به سبد خرید شما افزوده شد..
        /// </summary>
        internal static string AddServiceToBookingSuccessfully {
            get {
                return ResourceManager.GetString("AddServiceToBookingSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درحال حاضر دیدگاهی ثبت نشده است.
        /// </summary>
        internal static string CommentsEmptyList {
            get {
                return ResourceManager.GetString("CommentsEmptyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب و ایمیل شما با موفقیت تایید شد. &lt;a href=&apos;{0}&apos;&gt;برای ورود به سایت کلیک کنید.&lt;/a&gt;.
        /// </summary>
        internal static string EmailConfirmationMessage {
            get {
                return ResourceManager.GetString("EmailConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای مشاهده وضعیت سفارش خود به &lt;a href=&quot;{0}&quot;&gt;سفارش های من&lt;/a&gt; در پنل کاربری خود مراجعه نمائید..
        /// </summary>
        internal static string PaymentProfileLink {
            get {
                return ResourceManager.GetString("PaymentProfileLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلمه عبور شما با موفقیت ریست شد. &lt;a href=&apos;{0}&apos;&gt;برای ورود کلیک کنید.&lt;/a&gt;.
        /// </summary>
        internal static string ResetPasswordConfirmationMessage {
            get {
                return ResourceManager.GetString("ResetPasswordConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیغام شما برای کارشناسان ما ارسال شد. پس از بررسی در صورت لزوم با شما تماس گرفته می شود.
        /// </summary>
        internal static string SendContact {
            get {
                return ResourceManager.GetString("SendContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا با &lt;a href=&apos;{0}&apos;&gt;اینجا کلیک کنید&lt;/a&gt; حساب خود را تأیید کنید..
        /// </summary>
        internal static string SendEmail {
            get {
                return ResourceManager.GetString("SendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اخیراً سفارشی با شماره {0} ثبت شد.
        ///
        ///برای تکمیل سفارش، به پنل ادمین و قسمت مدیریت سفارشات به آدرس زیر مراجعه کنید:
        ///
        ///{1}.
        /// </summary>
        internal static string SendEmailCompleteBookingForAdmin {
            get {
                return ResourceManager.GetString("SendEmailCompleteBookingForAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سلام {0}
        /// 
        ///سفارش ما با شماره {1} با موفقیت ثبت شد.
        ///
        ///برای مشاهده جزعیات سفارش، به پنل کاربری و قسمت مدیریت سفارشات به آدرس زیر مراجعه کنید:
        ///
        ///{2}.
        /// </summary>
        internal static string SendEmailCompleteBookingForUser {
            get {
                return ResourceManager.GetString("SendEmailCompleteBookingForUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سلام {0}
        ///شما اخیراً درخواست بازیابی کلمه عبور حساب خود را داده اید.
        ///
        ///برای تکمیل فرایند، لطفاً از کد زیر استفاده کنید:
        ///{1}
        ///
        ///===============================================
        ///
        ///در ضمن رمز عبور موقت شما برای ورود به سایت به شرح زیر است:
        ///{2}
        ///
        ///
        ///لطفا پس از ورود به سایت رمز موقت را از طریق لینک زیر تغییر دهید.
        ///{3}
        ///
        ///
        ///با تشکر.
        /// </summary>
        internal static string SendEmailSignUpVerification {
            get {
                return ResourceManager.GetString("SendEmailSignUpVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سلام {0}
        /// 
        ///شما اخیراً در سایت آویس ثبت نام کرده اید.
        ///برای تکمیل ثبت نام، لطفاً حساب خود را تأیید کنید.
        ///
        ///ممکن است از شما خواسته شود این کد تأیید را وارد کنید: 
        ///{1}.
        /// </summary>
        internal static string SendEmailVerificationCode {
            get {
                return ResourceManager.GetString("SendEmailVerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سلام {0}
        ///شما اخیراً درخواست بازیابی کلمه عبور حساب خود را داده اید.
        ///
        ///برای تکمیل فرایند، لطفاً از کد زیر استفاده کنید:
        ///{1}.
        /// </summary>
        internal static string SendResetPasswordCode {
            get {
                return ResourceManager.GetString("SendResetPasswordCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تایید ایمیل حساب کاربری.
        /// </summary>
        internal static string SubjectEmail {
            get {
                return ResourceManager.GetString("SubjectEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت سفارش.
        /// </summary>
        internal static string SubjectEmailCompleteBookingForUser {
            get {
                return ResourceManager.GetString("SubjectEmailCompleteBookingForUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت سفارش.
        /// </summary>
        internal static string SubjectEmailCompleteBookingForUser1 {
            get {
                return ResourceManager.GetString("SubjectEmailCompleteBookingForUser1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایمیل و حساب کاربری خود را با استفاده از کد تایید کنید.
        /// </summary>
        internal static string SubjectEmaiVerificationCode {
            get {
                return ResourceManager.GetString("SubjectEmaiVerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بازیابی رمز عبور.
        /// </summary>
        internal static string SubjectResetPasswordEmail {
            get {
                return ResourceManager.GetString("SubjectResetPasswordEmail", resourceCulture);
            }
        }
    }
}
