//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Successes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Successes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Messages.Successes", typeof(Successes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات موفقیت آمیز بود..
        /// </summary>
        public static string ActionIsSuccessfully {
            get {
                return ResourceManager.GetString("ActionIsSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره تلفن همراه با موفقیت تایید گردید..
        /// </summary>
        public static string CellPhoneNumberVerified {
            get {
                return ResourceManager.GetString("CellPhoneNumberVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقد و بررسی شما با موفقیت ثبت شد. پس از بررسی توسط مدیر سایت به نمایش گذاشته می شود..
        /// </summary>
        public static string CommentSend {
            get {
                return ResourceManager.GetString("CommentSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نشانی پست الکترونیکی با موفقیت تایید گردید..
        /// </summary>
        public static string EmailAddressVerified {
            get {
                return ResourceManager.GetString("EmailAddressVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سفارش شما با موفقیت پرداخت و نهایی شد. کد پیگیری:  {0}.
        /// </summary>
        public static string PaymentResult {
            get {
                return ResourceManager.GetString("PaymentResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات {0} با موفقیت درج گردید..
        /// </summary>
        public static string SuccessCreate {
            get {
                return ResourceManager.GetString("SuccessCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات {0} با موفقیت حذف گردید..
        /// </summary>
        public static string SuccessDelete {
            get {
                return ResourceManager.GetString("SuccessDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لینک بازیابی رمزعبور با موفقیت به آدرس ایمیل شما {0} ارسال شد. برای بازیابی روی لینک موجود در ایمیل ارسالی ما کلیک نمائید..
        /// </summary>
        public static string SuccessSendEmailResetPassword {
            get {
                return ResourceManager.GetString("SuccessSendEmailResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لینک فعال سازی ایمیل با موفقیت به آدرس ایمیل شما {0} ارسال شد. برای فعال سازی روی لینک موجود در ایمیل ارسالی ما کلیک نمائید..
        /// </summary>
        public static string SuccessSendEmailVerification {
            get {
                return ResourceManager.GetString("SuccessSendEmailVerification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شما با موفقیت وارد سایت شدید..
        /// </summary>
        public static string SuccessSignIn {
            get {
                return ResourceManager.GetString("SuccessSignIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to با موفقیت از سیستم خارج شدید..
        /// </summary>
        public static string SuccessSignOut {
            get {
                return ResourceManager.GetString("SuccessSignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات {0} با موفقیت ویرایش گردید..
        /// </summary>
        public static string SuccessUpdate {
            get {
                return ResourceManager.GetString("SuccessUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فایل با موفقیت بارگزاری شد..
        /// </summary>
        public static string SuccessUploadFile {
            get {
                return ResourceManager.GetString("SuccessUploadFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گذرواژه با موفقیت تغییر کرد..
        /// </summary>
        public static string SuccessUserPasswordChanged {
            get {
                return ResourceManager.GetString("SuccessUserPasswordChanged", resourceCulture);
            }
        }
    }
}
