//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.Messages {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Validations {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Validations() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Messages.Validations", typeof(Validations).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حطایی در سرور رخ داد.
        /// </summary>
        public static string BadRequestException {
            get {
                return ResourceManager.GetString("BadRequestException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تکرار کلمه عبور با کلمه عبور وارد شده یکسان نیست..
        /// </summary>
        public static string ComparePasswordIsInValid {
            get {
                return ResourceManager.GetString("ComparePasswordIsInValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} باید بین {2} تا {1} درصد باشد.
        /// </summary>
        public static string DiscountRangeInvalid {
            get {
                return ResourceManager.GetString("DiscountRangeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایمیل وارد شده صحیح نیست..
        /// </summary>
        public static string EmailAddressInvalid {
            get {
                return ResourceManager.GetString("EmailAddressInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار فیلد {0} باید دقیقا {1} رقم باشد!.
        /// </summary>
        public static string FixLengthNumeric {
            get {
                return ResourceManager.GetString("FixLengthNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار فیلد {0} باید بزرگ‌تر از {1} باشد!.
        /// </summary>
        public static string GreaterThan_FieldValue {
            get {
                return ResourceManager.GetString("GreaterThan_FieldValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار فیلد {0} باید بزرگ‌تر از مقدار فیلد {1} باشد!.
        /// </summary>
        public static string GreaterThan_TwoFields {
            get {
                return ResourceManager.GetString("GreaterThan_TwoFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار فیلد {0} باید بزرگ‌تر یا مساوی {1} باشد!.
        /// </summary>
        public static string GreaterThanOrEqualTo_FieldValue {
            get {
                return ResourceManager.GetString("GreaterThanOrEqualTo_FieldValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار فیلد {0} باید بزرگ‌تر یا مساوی مقدار فیلد {1} باشد!.
        /// </summary>
        public static string GreaterThanOrEqualTo_TwoFields {
            get {
                return ResourceManager.GetString("GreaterThanOrEqualTo_TwoFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد {0} صحیح نمی‌باشد!.
        /// </summary>
        public static string InvalidCode {
            get {
                return ResourceManager.GetString("InvalidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token is invalid: {0}.
        /// </summary>
        public static string JwtDecodeTokenIsInvalid {
            get {
                return ResourceManager.GetString("JwtDecodeTokenIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خطایی رخ داد!.
        /// </summary>
        public static string LogicException {
            get {
                return ResourceManager.GetString("LogicException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طول فیلد {0} می‌تواند حداکثر {1} کاراکتر باشد!.
        /// </summary>
        public static string MaxLength {
            get {
                return ResourceManager.GetString("MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طول فیلد {PropertyName} می‌تواند حداکثر {MaxLength} کاراکتر باشد!.
        /// </summary>
        public static string MaxLengthFluent {
            get {
                return ResourceManager.GetString("MaxLengthFluent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طول فیلد {0} باید حداقل {1} کاراکتر باشد!.
        /// </summary>
        public static string MinLength {
            get {
                return ResourceManager.GetString("MinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طول فیلد {PropertyName} باید حداقل {MinLength} کاراکتر باشد!.
        /// </summary>
        public static string MinLengthFluent {
            get {
                return ResourceManager.GetString("MinLengthFluent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد ملی وارد شده صحیح نیست!.
        /// </summary>
        public static string NationalCodeIsInvalid {
            get {
                return ResourceManager.GetString("NationalCodeIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} یافت نشد!.
        /// </summary>
        public static string NotFound {
            get {
                return ResourceManager.GetString("NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to چیزی یافت نشد!.
        /// </summary>
        public static string NotFoundException {
            get {
                return ResourceManager.GetString("NotFoundException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فقط حروف انگلیسی مجاز است!.
        /// </summary>
        public static string OnlyTypeEnglish {
            get {
                return ResourceManager.GetString("OnlyTypeEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فقط اعداد مجاز است!.
        /// </summary>
        public static string OnlyTypeNumbers {
            get {
                return ResourceManager.GetString("OnlyTypeNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلمه عبور باید حداقل 6 کاراکتر طول داشته باشد و ترکیبی از اعداد (&apos;0&apos;-&apos;9&apos;) و حروف انگلیسی کوچک (&apos;a&apos;-&apos;z&apos;) باشد..
        /// </summary>
        public static string PasswordIsInvalid {
            get {
                return ResourceManager.GetString("PasswordIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره همراه وارد شده صحیح نیست..
        /// </summary>
        public static string PhoneNumberIsInvalid {
            get {
                return ResourceManager.GetString("PhoneNumberIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد پستی وارد شده صحیح نیست..
        /// </summary>
        public static string PostalCodeIsInvalid {
            get {
                return ResourceManager.GetString("PostalCodeIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد مجاز در سبد خرید فقط یک عدد میباشد.
        /// </summary>
        public static string QuantityRangeInvalid {
            get {
                return ResourceManager.GetString("QuantityRangeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار فیلد {0} باید بزرگ‌تر یا مساوی {1} و کوچک‌تر یا مساوی {2} باشد..
        /// </summary>
        public static string Range {
            get {
                return ResourceManager.GetString("Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} باید بین {2} تا {1} باشد.
        /// </summary>
        public static string RangeInvalid {
            get {
                return ResourceManager.GetString("RangeInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {PropertyName} باید بین {MaxLength} تا {MinLength} باشد.
        /// </summary>
        public static string RangeInvalidFluent {
            get {
                return ResourceManager.GetString("RangeInvalidFluent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار {0} معتبر نمی‌باشد!.
        /// </summary>
        public static string RegularExpression {
            get {
                return ResourceManager.GetString("RegularExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} تکراری است! لطفا از {0} دیگری استفاده نمایید..
        /// </summary>
        public static string Repetitive {
            get {
                return ResourceManager.GetString("Repetitive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تکمیل {0} الزامی است!.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تکمیل {PropertyName} الزامی است!.
        /// </summary>
        public static string RequiredFluent {
            get {
                return ResourceManager.GetString("RequiredFluent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} باید بین {2} تا {1} کاراکتر باشد.
        /// </summary>
        public static string StringLength {
            get {
                return ResourceManager.GetString("StringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد وارد شده صحیح نیست!.
        /// </summary>
        public static string VerificationCodeIsInvalid {
            get {
                return ResourceManager.GetString("VerificationCodeIsInvalid", resourceCulture);
            }
        }
    }
}
