version: 2.1
workflows:
  deployment:
    jobs:
      - build-api
      - build-backend
jobs:
  build-api:
    machine: true
    resource_class: ravil/pipeline
    parallelism: 2
    steps:
      - checkout
      - run:
          name: Cleanup Old Containers
          when: always
          command: docker rm -f API || true

      - run:
          name: Build Docker Image
          command: |
            docker build -f ./Dockerfile-api -t api .

      - run:
          name: Run Docker Container
          command: |
            docker run -d \
              --name API \
              -p 9090:8080 \
              --network bridge \
              --restart unless-stopped \
              api

  build-backend:
    machine: true
    resource_class: ravil/pipeline
    parallelism: 2
    steps:
      - checkout
      - run:
          name: Cleanup Old Containers
          when: always
          command: docker rm -f Backend || true

      - run:
          name: Build Docker Image
          command: |
            docker build -t backend .

      - run:
          name: Run Docker Container
          command: |
            docker run -d \
              --name Backend \
              -p 8080:8080 \
              --network bridge \
              --restart unless-stopped \
              backend