//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources.General {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DisplayNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DisplayNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.General.DisplayNames", typeof(DisplayNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صفحه درباره ما.
        /// </summary>
        public static string AboutPage {
            get {
                return ResourceManager.GetString("AboutPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محتوا و توضیحات صفحه درباره ما.
        /// </summary>
        public static string AboutUsContent {
            get {
                return ResourceManager.GetString("AboutUsContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توضیحات متا صفحه درباره ما.
        /// </summary>
        public static string AboutUsMetaDescription {
            get {
                return ResourceManager.GetString("AboutUsMetaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توضیحات بخش ماموریت ها.
        /// </summary>
        public static string AboutUsOurMissionDescription {
            get {
                return ResourceManager.GetString("AboutUsOurMissionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان بخش ماموریت ها.
        /// </summary>
        public static string AboutUsOurMissionTitle {
            get {
                return ResourceManager.GetString("AboutUsOurMissionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توضیحات بخش ارزش ها.
        /// </summary>
        public static string AboutUsOurValuesDescription {
            get {
                return ResourceManager.GetString("AboutUsOurValuesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان بخش ارزش ها.
        /// </summary>
        public static string AboutUsOurValuesTitle {
            get {
                return ResourceManager.GetString("AboutUsOurValuesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان صفحه درباره ما.
        /// </summary>
        public static string AboutUsTitle {
            get {
                return ResourceManager.GetString("AboutUsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویدئو صفحه درباره ما.
        /// </summary>
        public static string AboutUsVideo {
            get {
                return ResourceManager.GetString("AboutUsVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاور ویدئو صفحه درباره ما.
        /// </summary>
        public static string AboutUsVideoCover {
            get {
                return ResourceManager.GetString("AboutUsVideoCover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صفحه عدم دسترسی به منابع.
        /// </summary>
        public static string AccessDeniedPageTitle {
            get {
                return ResourceManager.GetString("AccessDeniedPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مخصوص اکانت.
        /// </summary>
        public static string AccountPage {
            get {
                return ResourceManager.GetString("AccountPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عملیات.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس.
        /// </summary>
        public static string AddressContactSection {
            get {
                return ResourceManager.GetString("AddressContactSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مدیر.
        /// </summary>
        public static string Administrator {
            get {
                return ResourceManager.GetString("Administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بزرگسالان.
        /// </summary>
        public static string Adults {
            get {
                return ResourceManager.GetString("Adults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نماینده.
        /// </summary>
        public static string Agent {
            get {
                return ResourceManager.GetString("Agent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پاسخ.
        /// </summary>
        public static string Answer {
            get {
                return ResourceManager.GetString("Answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آپارات.
        /// </summary>
        public static string Aparat {
            get {
                return ResourceManager.GetString("Aparat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ ورود.
        /// </summary>
        public static string ArrivalDate {
            get {
                return ResourceManager.GetString("ArrivalDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ادمین.
        /// </summary>
        public static string AuthDropdownSectionAdminPanelLinkText {
            get {
                return ResourceManager.GetString("AuthDropdownSectionAdminPanelLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خروج از سایت.
        /// </summary>
        public static string AuthDropdownSectionLogoutLinkText {
            get {
                return ResourceManager.GetString("AuthDropdownSectionLogoutLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پروفایل کاربری.
        /// </summary>
        public static string AuthDropdownSectionProfileLinkText {
            get {
                return ResourceManager.GetString("AuthDropdownSectionProfileLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نویسنده.
        /// </summary>
        public static string AuthorName {
            get {
                return ResourceManager.GetString("AuthorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد ارسال شده را برای تایید و فعال سازی حساب کاربری وارد کنید ....
        /// </summary>
        public static string AuthPageCodePlaceholderText {
            get {
                return ResourceManager.GetString("AuthPageCodePlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تکرار رمز عبور ....
        /// </summary>
        public static string AuthPageConfirmPasswordPlaceholderText {
            get {
                return ResourceManager.GetString("AuthPageConfirmPasswordPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس ایمیل خود را وارد کنید ....
        /// </summary>
        public static string AuthPageEmailAddressPlaceholderText {
            get {
                return ResourceManager.GetString("AuthPageEmailAddressPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورود با حساب.
        /// </summary>
        public static string AuthPageExternalButtonText {
            get {
                return ResourceManager.GetString("AuthPageExternalButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورود با فیسبوک.
        /// </summary>
        public static string AuthPageExternalFacebookButtonText {
            get {
                return ResourceManager.GetString("AuthPageExternalFacebookButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورود با گوگل.
        /// </summary>
        public static string AuthPageExternalGoogleButtonText {
            get {
                return ResourceManager.GetString("AuthPageExternalGoogleButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام خود را وارد کنید ....
        /// </summary>
        public static string AuthPageFirstNamePlaceholderText {
            get {
                return ResourceManager.GetString("AuthPageFirstNamePlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فراموشی کلمه عبور.
        /// </summary>
        public static string AuthPageForgotPasswordLinkText {
            get {
                return ResourceManager.GetString("AuthPageForgotPasswordLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام خانوادگی خود را وارد کنید ....
        /// </summary>
        public static string AuthPageLastNamePlaceholderText {
            get {
                return ResourceManager.GetString("AuthPageLastNamePlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور خود را وارد کنید ....
        /// </summary>
        public static string AuthPagePasswordPlaceholderText {
            get {
                return ResourceManager.GetString("AuthPagePasswordPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رایگان ثبت نام کنید.
        /// </summary>
        public static string AuthPageRegisterQuestionLinkText {
            get {
                return ResourceManager.GetString("AuthPageRegisterQuestionLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب کاربری ندارید ؟.
        /// </summary>
        public static string AuthPageRegisterQuestionText {
            get {
                return ResourceManager.GetString("AuthPageRegisterQuestionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا وارد شوید.
        /// </summary>
        public static string AuthPageSignInQuestionLinkText {
            get {
                return ResourceManager.GetString("AuthPageSignInQuestionLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب کاربری ندارید ؟.
        /// </summary>
        public static string AuthPageSignInQuestionText {
            get {
                return ResourceManager.GetString("AuthPageSignInQuestionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری یا ایمل خود را وارد کنید ....
        /// </summary>
        public static string AuthPageUsernamePlaceholderText {
            get {
                return ResourceManager.GetString("AuthPageUsernamePlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آواتار.
        /// </summary>
        public static string Avatar {
            get {
                return ResourceManager.GetString("Avatar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to میانگین رضایت.
        /// </summary>
        public static string AverageOfRate {
            get {
                return ResourceManager.GetString("AverageOfRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوزاد.
        /// </summary>
        public static string Baby {
            get {
                return ResourceManager.GetString("Baby", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تصویر بنر.
        /// </summary>
        public static string BannerPicture {
            get {
                return ResourceManager.GetString("BannerPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ تولد.
        /// </summary>
        public static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وبلاگ.
        /// </summary>
        public static string Blog {
            get {
                return ResourceManager.GetString("Blog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محتوا صفحه مجله پزشکی.
        /// </summary>
        public static string BlogHeadingContent {
            get {
                return ResourceManager.GetString("BlogHeadingContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توضیحات لیست صفحه مجله پزشکی.
        /// </summary>
        public static string BlogListHeadCopyWrite {
            get {
                return ResourceManager.GetString("BlogListHeadCopyWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توضیحات متا صفحه مجله پزشکی.
        /// </summary>
        public static string BlogMetaDescription {
            get {
                return ResourceManager.GetString("BlogMetaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مخصوص وبلاگ.
        /// </summary>
        public static string BlogPage {
            get {
                return ResourceManager.GetString("BlogPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان صفحه مجله پزشکی.
        /// </summary>
        public static string BlogTitle {
            get {
                return ResourceManager.GetString("BlogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره سریال.
        /// </summary>
        public static string BookigNumber {
            get {
                return ResourceManager.GetString("BookigNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نشان کردن.
        /// </summary>
        public static string BookmarkButtonText {
            get {
                return ResourceManager.GetString("BookmarkButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هردو.
        /// </summary>
        public static string Both {
            get {
                return ResourceManager.GetString("Both", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آویسن.
        /// </summary>
        public static string BrandName {
            get {
                return ResourceManager.GetString("BrandName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کنونیکال شود؟.
        /// </summary>
        public static string CanonicalMeta {
            get {
                return ResourceManager.GetString("CanonicalMeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لینک کنونیکال.
        /// </summary>
        public static string CanonicalMetaUrl {
            get {
                return ResourceManager.GetString("CanonicalMetaUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسته بندی.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مخصوص دسته بندی.
        /// </summary>
        public static string CategoryPage {
            get {
                return ResourceManager.GetString("CategoryPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره تلفن همراه.
        /// </summary>
        public static string CellPhoneNumber {
            get {
                return ResourceManager.GetString("CellPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد تایید شماره تلفن همراه.
        /// </summary>
        public static string CellPhoneNumberVerificationKey {
            get {
                return ResourceManager.GetString("CellPhoneNumberVerificationKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کودکان.
        /// </summary>
        public static string Children {
            get {
                return ResourceManager.GetString("Children", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شهر.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام شهر.
        /// </summary>
        public static string CityName {
            get {
                return ResourceManager.GetString("CityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مخصوص شهر.
        /// </summary>
        public static string CityPage {
            get {
                return ResourceManager.GetString("CityPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان بستری.
        /// </summary>
        public static string ClinicStay {
            get {
                return ResourceManager.GetString("ClinicStay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بستن.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صفحه وبلاگ.
        /// </summary>
        public static string CmsPage {
            get {
                return ResourceManager.GetString("CmsPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دیدگاه.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درصد رضایت بیماران.
        /// </summary>
        public static string CommentPercentAverage {
            get {
                return ResourceManager.GetString("CommentPercentAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نظر.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لایک کردن دیدگاه.
        /// </summary>
        public static string CommentsSectionLikeTooltipText {
            get {
                return ResourceManager.GetString("CommentsSectionLikeTooltipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این پزشک پیشنهاد میشود.
        /// </summary>
        public static string CommentsSectionRecommendedDoctorText {
            get {
                return ResourceManager.GetString("CommentsSectionRecommendedDoctorText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پاسخ به دیدگاه.
        /// </summary>
        public static string CommentsSectionReplyTooltipText {
            get {
                return ResourceManager.GetString("CommentsSectionReplyTooltipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جستجو نظر، نام کاربر یا بیمار.
        /// </summary>
        public static string CommentsSectionSearchPlaceholderText {
            get {
                return ResourceManager.GetString("CommentsSectionSearchPlaceholderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشاهده بیشتر.
        /// </summary>
        public static string CommentsSectionSeeMoreButtonText {
            get {
                return ResourceManager.GetString("CommentsSectionSeeMoreButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام شرکت.
        /// </summary>
        public static string CompanyName {
            get {
                return ResourceManager.GetString("CompanyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تایید ایمیل و حساب کاربری.
        /// </summary>
        public static string ConfirmEmailPageTitle {
            get {
                return ResourceManager.GetString("ConfirmEmailPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تکرار رمز عبور.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسال پیام.
        /// </summary>
        public static string ContactFormButtonTitle {
            get {
                return ResourceManager.GetString("ContactFormButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صفحه تماس باما.
        /// </summary>
        public static string ContactPage {
            get {
                return ResourceManager.GetString("ContactPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تصویر شاخص صفحه تماس باما.
        /// </summary>
        public static string ContactPageImage {
            get {
                return ResourceManager.GetString("ContactPageImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویدئو صفحه تماس باما.
        /// </summary>
        public static string ContactPageVideo {
            get {
                return ResourceManager.GetString("ContactPageVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تماس با ما.
        /// </summary>
        public static string ContactUs {
            get {
                return ResourceManager.GetString("ContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محتوا.
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فهرست مطالب.
        /// </summary>
        public static string ContentTitles {
            get {
                return ResourceManager.GetString("ContentTitles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد.
        /// </summary>
        public static string Count {
            get {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua..
        /// </summary>
        public static string CountriesComponentHeadingDescription {
            get {
                return ResourceManager.GetString("CountriesComponentHeadingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ما خدمات پزشکی را ارائه کرده ایم.
        /// </summary>
        public static string CountriesComponentHeadingTitle {
            get {
                return ResourceManager.GetString("CountriesComponentHeadingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کشور.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تصویر کاور.
        /// </summary>
        public static string CoverPicture {
            get {
                return ResourceManager.GetString("CoverPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسال دیدگاه.
        /// </summary>
        public static string CreateCommentButtonText {
            get {
                return ResourceManager.GetString("CreateCommentButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جستجو نظرات، کاربران و بیماران ....
        /// </summary>
        public static string CreateCommentSearchPlaceholder {
            get {
                return ResourceManager.GetString("CreateCommentSearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرتب سازی.
        /// </summary>
        public static string CreateCommentSortButtonText {
            get {
                return ResourceManager.GetString("CreateCommentSortButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دیدگاه خود را ارسال کنید:.
        /// </summary>
        public static string CreateCommentText {
            get {
                return ResourceManager.GetString("CreateCommentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ ثبت.
        /// </summary>
        public static string CreateDate {
            get {
                return ResourceManager.GetString("CreateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سفر شما به سمت سلامتی از اینجا شروع می شود.
        /// </summary>
        public static string CtaComponentHeadingDesciption {
            get {
                return ResourceManager.GetString("CtaComponentHeadingDesciption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سفر شما به سمت سلامتی از اینجا شروع می شود.
        /// </summary>
        public static string CtaComponentHeadingTitle {
            get {
                return ResourceManager.GetString("CtaComponentHeadingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to واحد پول.
        /// </summary>
        public static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد واحد پول.
        /// </summary>
        public static string CurrencyCode {
            get {
                return ResourceManager.GetString("CurrencyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ جاری.
        /// </summary>
        public static string CurrentDate {
            get {
                return ResourceManager.GetString("CurrentDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غیرفعال.
        /// </summary>
        public static string DeActive {
            get {
                return ResourceManager.GetString("DeActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر.
        /// </summary>
        public static string DefaultUserFirstName {
            get {
                return ResourceManager.GetString("DefaultUserFirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سایت.
        /// </summary>
        public static string DefaultUserLastName {
            get {
                return ResourceManager.GetString("DefaultUserLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ حذف.
        /// </summary>
        public static string DeleteDate {
            get {
                return ResourceManager.GetString("DeleteDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to واریز.
        /// </summary>
        public static string Deposit {
            get {
                return ResourceManager.GetString("Deposit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توضیح.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تخفیف.
        /// </summary>
        public static string Discount {
            get {
                return ResourceManager.GetString("Discount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to میزان تخفیف.
        /// </summary>
        public static string DiscountAmount {
            get {
                return ResourceManager.GetString("DiscountAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد تخفیف.
        /// </summary>
        public static string DiscountCode {
            get {
                return ResourceManager.GetString("DiscountCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کوپن تخفیف.
        /// </summary>
        public static string DiscountCoupon {
            get {
                return ResourceManager.GetString("DiscountCoupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درصد تخفیف.
        /// </summary>
        public static string DiscountPercent {
            get {
                return ResourceManager.GetString("DiscountPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قیمت تخفیف.
        /// </summary>
        public static string DiscountPrice {
            get {
                return ResourceManager.GetString("DiscountPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نپسندیدن.
        /// </summary>
        public static string Dislike {
            get {
                return ResourceManager.GetString("Dislike", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویرایش.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نشانی پست الکترونیکی.
        /// </summary>
        public static string EmailAddress {
            get {
                return ResourceManager.GetString("EmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد تایید نشانی پست الکترونیکی.
        /// </summary>
        public static string EmailAddressVerificationKey {
            get {
                return ResourceManager.GetString("EmailAddressVerificationKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد عمل جراحی و سبقه.
        /// </summary>
        public static string ExperienceCount {
            get {
                return ResourceManager.GetString("ExperienceCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ انقضاء.
        /// </summary>
        public static string ExpireDate {
            get {
                return ResourceManager.GetString("ExpireDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرمت فایل.
        /// </summary>
        public static string Extension {
            get {
                return ResourceManager.GetString("Extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فیسبوک.
        /// </summary>
        public static string Facebook {
            get {
                return ResourceManager.GetString("Facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سوالات متداول.
        /// </summary>
        public static string Faqs {
            get {
                return ResourceManager.GetString("Faqs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua..
        /// </summary>
        public static string FaqsComponentHeadingDescription {
            get {
                return ResourceManager.GetString("FaqsComponentHeadingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سوالات متداول شما.
        /// </summary>
        public static string FaqsComponentHeadingTitle {
            get {
                return ResourceManager.GetString("FaqsComponentHeadingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فکس.
        /// </summary>
        public static string FaxNumber {
            get {
                return ResourceManager.GetString("FaxNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خانم.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع فایل.
        /// </summary>
        public static string FileType {
            get {
                return ResourceManager.GetString("FileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سایر دسته بندی ها.
        /// </summary>
        public static string FilterCategoryTitle {
            get {
                return ResourceManager.GetString("FilterCategoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فیلترهای بیشتر.
        /// </summary>
        public static string FilterMoreTitle {
            get {
                return ResourceManager.GetString("FilterMoreTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بازه قیمتی.
        /// </summary>
        public static string FilterPricementTitle {
            get {
                return ResourceManager.GetString("FilterPricementTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرتب سازی.
        /// </summary>
        public static string FilterSortHeadingTitle {
            get {
                return ResourceManager.GetString("FilterSortHeadingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مرتب سازی.
        /// </summary>
        public static string FilterSortingTitle {
            get {
                return ResourceManager.GetString("FilterSortingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محبوب ترین.
        /// </summary>
        public static string FilterSortPopular {
            get {
                return ResourceManager.GetString("FilterSortPopular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارزان ترین.
        /// </summary>
        public static string FilterSortPriceAsc {
            get {
                return ResourceManager.GetString("FilterSortPriceAsc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گران ترین.
        /// </summary>
        public static string FilterSortPriceDesc {
            get {
                return ResourceManager.GetString("FilterSortPriceDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آخرین.
        /// </summary>
        public static string FilterSortRecent {
            get {
                return ResourceManager.GetString("FilterSortRecent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فالو شود؟.
        /// </summary>
        public static string FollowMeta {
            get {
                return ResourceManager.GetString("FollowMeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تایید و مرحله بعدی.
        /// </summary>
        public static string ForgetPasswordFormButtonTitle {
            get {
                return ResourceManager.GetString("ForgetPasswordFormButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای بازیابی رمز حساب کاربری، ایمیل خود را وارد کنید..
        /// </summary>
        public static string ForgetPasswordPageDescription {
            get {
                return ResourceManager.GetString("ForgetPasswordPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فراموشی رمز عبور.
        /// </summary>
        public static string ForgetPasswordPageHeadingTitle {
            get {
                return ResourceManager.GetString("ForgetPasswordPageHeadingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ما یک ایمیل حاوی کد بازیابی کلمه عبور به شماره حساب ایمیل شما ارسال خواهیم کرد..
        /// </summary>
        public static string ForgetPasswordPageNote {
            get {
                return ResourceManager.GetString("ForgetPasswordPageNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فراموشی رمز عبور.
        /// </summary>
        public static string ForgetPasswordPageTitle {
            get {
                return ResourceManager.GetString("ForgetPasswordPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیدا شد 302.
        /// </summary>
        public static string Found302 {
            get {
                return ResourceManager.GetString("Found302", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام و نام خانوادگی.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جنسیت.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محتوای حذف شده 410.
        /// </summary>
        public static string Gone410 {
            get {
                return ResourceManager.GetString("Gone410", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گروه.
        /// </summary>
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برداشت.
        /// </summary>
        public static string Harvest {
            get {
                return ResourceManager.GetString("Harvest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورود / ثبت نام.
        /// </summary>
        public static string HeaderAuthButtonText {
            get {
                return ResourceManager.GetString("HeaderAuthButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جستوجو.
        /// </summary>
        public static string HeaderSearchButtonText {
            get {
                return ResourceManager.GetString("HeaderSearchButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جستوجو در بین پزشکان، خدمات و ....
        /// </summary>
        public static string HeaderSearchPlaceholder {
            get {
                return ResourceManager.GetString("HeaderSearchPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صفحه اصلی.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توضیحات بخش معرفی و درباره ما صفحه اصلی.
        /// </summary>
        public static string HomeAboutSectionContent {
            get {
                return ResourceManager.GetString("HomeAboutSectionContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان بخش معرفی و درباره ما صفحه اصلی.
        /// </summary>
        public static string HomeAboutSectionTitle {
            get {
                return ResourceManager.GetString("HomeAboutSectionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توضیحات صفحه اصلی.
        /// </summary>
        public static string HomeDescription {
            get {
                return ResourceManager.GetString("HomeDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توضیحات متا صفحه اصلی.
        /// </summary>
        public static string HomeMetaDescription {
            get {
                return ResourceManager.GetString("HomeMetaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مخصوص صفحه اصلی.
        /// </summary>
        public static string HomePage {
            get {
                return ResourceManager.GetString("HomePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تصویر شاخص صفحه اصلی.
        /// </summary>
        public static string HomePageImage {
            get {
                return ResourceManager.GetString("HomePageImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویدئو اینترو صفحه اصلی.
        /// </summary>
        public static string HomePageIntroductionVideo {
            get {
                return ResourceManager.GetString("HomePageIntroductionVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاور ویدئو اینترو صفحه اصلی.
        /// </summary>
        public static string HomePageIntroductionVideoCover {
            get {
                return ResourceManager.GetString("HomePageIntroductionVideoCover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویدئو صفحه اصلی.
        /// </summary>
        public static string HomePageVideo {
            get {
                return ResourceManager.GetString("HomePageVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاور ویدئو صفحه اصلی.
        /// </summary>
        public static string HomePageVideoCover {
            get {
                return ResourceManager.GetString("HomePageVideoCover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان صفحه اصلی.
        /// </summary>
        public static string HomeTitle {
            get {
                return ResourceManager.GetString("HomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیکن.
        /// </summary>
        public static string Icon {
            get {
                return ResourceManager.GetString("Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه.
        /// </summary>
        public static string Id {
            get {
                return ResourceManager.GetString("Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تصویر.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایندکس شود؟.
        /// </summary>
        public static string IndexMeta {
            get {
                return ResourceManager.GetString("IndexMeta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اینستاگرام.
        /// </summary>
        public static string Instagram {
            get {
                return ResourceManager.GetString("Instagram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویدئو معرفی.
        /// </summary>
        public static string IntroductionVideo {
            get {
                return ResourceManager.GetString("IntroductionVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاور ویدئو معرفی.
        /// </summary>
        public static string IntroductionVideoCover {
            get {
                return ResourceManager.GetString("IntroductionVideoCover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موجودی.
        /// </summary>
        public static string Inventory {
            get {
                return ResourceManager.GetString("Inventory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فعال.
        /// </summary>
        public static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره تلفن همراه تایید شده است.
        /// </summary>
        public static string IsCellPhoneNumberVerified {
            get {
                return ResourceManager.GetString("IsCellPhoneNumberVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت تایید.
        /// </summary>
        public static string IsConfirmed {
            get {
                return ResourceManager.GetString("IsConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انداختن در سطل زباله.
        /// </summary>
        public static string IsDeleted {
            get {
                return ResourceManager.GetString("IsDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نشانی پست الکترونیکی تایید شده است.
        /// </summary>
        public static string IsEmailAddressVerified {
            get {
                return ResourceManager.GetString("IsEmailAddressVerified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to باخورد مثبت است؟.
        /// </summary>
        public static string IsFeedbackPositive {
            get {
                return ResourceManager.GetString("IsFeedbackPositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کسب و کار.
        /// </summary>
        public static string JobBranch {
            get {
                return ResourceManager.GetString("JobBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مخصوص کسب و کار.
        /// </summary>
        public static string JobBranchPage {
            get {
                return ResourceManager.GetString("JobBranchPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زبان.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد زبان.
        /// </summary>
        public static string LanguageCode {
            get {
                return ResourceManager.GetString("LanguageCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خلاصه زبان.
        /// </summary>
        public static string LanguageSummary {
            get {
                return ResourceManager.GetString("LanguageSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام خانوادگی.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ بروزرسانی.
        /// </summary>
        public static string LastUpdateDate {
            get {
                return ResourceManager.GetString("LastUpdateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جدید ترین ها.
        /// </summary>
        public static string LatestJobs {
            get {
                return ResourceManager.GetString("LatestJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پسندیدن.
        /// </summary>
        public static string Like {
            get {
                return ResourceManager.GetString("Like", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لینکدین.
        /// </summary>
        public static string LinkedIn {
            get {
                return ResourceManager.GetString("LinkedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موردی برای نمایش وجود ندارد!.
        /// </summary>
        public static string ListEmpty {
            get {
                return ResourceManager.GetString("ListEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لوگو.
        /// </summary>
        public static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آقا.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خانم و آقا.
        /// </summary>
        public static string MaleAndFemale {
            get {
                return ResourceManager.GetString("MaleAndFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقشه.
        /// </summary>
        public static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیوند نقشه.
        /// </summary>
        public static string MapUrl {
            get {
                return ResourceManager.GetString("MapUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد نظام پزشکی.
        /// </summary>
        public static string MedicalSystemCode {
            get {
                return ResourceManager.GetString("MedicalSystemCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بازگشت به منو اصلی.
        /// </summary>
        public static string MenuBackButtonText {
            get {
                return ResourceManager.GetString("MenuBackButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بستن منو.
        /// </summary>
        public static string MenuCloseButtonText {
            get {
                return ResourceManager.GetString("MenuCloseButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توضیحات متا سئو.
        /// </summary>
        public static string MetaDescription {
            get {
                return ResourceManager.GetString("MetaDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان متا سئو.
        /// </summary>
        public static string MetaTitle {
            get {
                return ResourceManager.GetString("MetaTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امتیاز.
        /// </summary>
        public static string MobileAverageOfRate {
            get {
                return ResourceManager.GetString("MobileAverageOfRate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تصویر موبایل.
        /// </summary>
        public static string MobilePicture {
            get {
                return ResourceManager.GetString("MobilePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیشنهاد لحظه ای.
        /// </summary>
        public static string MomentJobs {
            get {
                return ResourceManager.GetString("MomentJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مبلغ.
        /// </summary>
        public static string Money {
            get {
                return ResourceManager.GetString("Money", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاملا انتقال یافت 301.
        /// </summary>
        public static string MovedPermanently301 {
            get {
                return ResourceManager.GetString("MovedPermanently301", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد ملی.
        /// </summary>
        public static string NationalCode {
            get {
                return ResourceManager.GetString("NationalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز عبور جدید.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمزعبور فعلی.
        /// </summary>
        public static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to یا.
        /// </summary>
        public static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سایر.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to والد.
        /// </summary>
        public static string Parent {
            get {
                return ResourceManager.GetString("Parent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گذرواژه.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پرداخت.
        /// </summary>
        public static string Payment {
            get {
                return ResourceManager.GetString("Payment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درصد.
        /// </summary>
        public static string Percent {
            get {
                return ResourceManager.GetString("Percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره تماس.
        /// </summary>
        public static string PhoneContactSection {
            get {
                return ResourceManager.GetString("PhoneContactSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره تماس ها.
        /// </summary>
        public static string PhoneNumbers {
            get {
                return ResourceManager.GetString("PhoneNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تلفن ثابت.
        /// </summary>
        public static string PhoneNumberTel {
            get {
                return ResourceManager.GetString("PhoneNumberTel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تصویر.
        /// </summary>
        public static string Picture {
            get {
                return ResourceManager.GetString("Picture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قیمت.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to محصول.
        /// </summary>
        public static string Product {
            get {
                return ResourceManager.GetString("Product", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مخصوص محصولات.
        /// </summary>
        public static string ProductPage {
            get {
                return ResourceManager.GetString("ProductPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استان.
        /// </summary>
        public static string Province {
            get {
                return ResourceManager.GetString("Province", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام استان.
        /// </summary>
        public static string ProvinceName {
            get {
                return ResourceManager.GetString("ProvinceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ناشر.
        /// </summary>
        public static string Publisher {
            get {
                return ResourceManager.GetString("Publisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سوال.
        /// </summary>
        public static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to میانگین امتیاز بیماران.
        /// </summary>
        public static string RateAverage {
            get {
                return ResourceManager.GetString("RateAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان خواندن.
        /// </summary>
        public static string ReadingTime {
            get {
                return ResourceManager.GetString("ReadingTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمان ریکاوری.
        /// </summary>
        public static string Recovery {
            get {
                return ResourceManager.GetString("Recovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ ثبت نام.
        /// </summary>
        public static string RegisterDate {
            get {
                return ResourceManager.GetString("RegisterDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من را بخاطر بسپار.
        /// </summary>
        public static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسال مجدد کد.
        /// </summary>
        public static string ResendCode {
            get {
                return ResourceManager.GetString("ResendCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بازیابی کلمه عبور انجام شد.
        /// </summary>
        public static string ResetPasswordConfirmationPageTitle {
            get {
                return ResourceManager.GetString("ResetPasswordConfirmationPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بازیابی.
        /// </summary>
        public static string ResetPasswordFormButtonTitle {
            get {
                return ResourceManager.GetString("ResetPasswordFormButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string ResetPasswordPageDescription {
            get {
                return ResourceManager.GetString("ResetPasswordPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بازیابی کلمه عبور.
        /// </summary>
        public static string ResetPasswordPageHeadingTitle {
            get {
                return ResourceManager.GetString("ResetPasswordPageHeadingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کلمه عبور مورد نظر خود را به همراه کد ارسال شده به ایمیل خود را وارد کنید..
        /// </summary>
        public static string ResetPasswordPageNote {
            get {
                return ResourceManager.GetString("ResetPasswordPageNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بازیابی کلمه عبور.
        /// </summary>
        public static string ResetPasswordPageTitle {
            get {
                return ResourceManager.GetString("ResetPasswordPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بررسی نمونه کار.
        /// </summary>
        public static string Review {
            get {
                return ResourceManager.GetString("Review", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صفحه بازخوردها.
        /// </summary>
        public static string ReviewPage {
            get {
                return ResourceManager.GetString("ReviewPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ردیف.
        /// </summary>
        public static string Row {
            get {
                return ResourceManager.GetString("Row", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قوانین و مقررات.
        /// </summary>
        public static string Rules {
            get {
                return ResourceManager.GetString("Rules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشاهده بیشتر.
        /// </summary>
        public static string SeeMore {
            get {
                return ResourceManager.GetString("SeeMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مشاهده.
        /// </summary>
        public static string Seen {
            get {
                return ResourceManager.GetString("Seen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اشتراک گزاری.
        /// </summary>
        public static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اشتراک گزاری.
        /// </summary>
        public static string ShareButtonText {
            get {
                return ResourceManager.GetString("ShareButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بستن.
        /// </summary>
        public static string ShareModalBackButtonText {
            get {
                return ResourceManager.GetString("ShareModalBackButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کپی لینک.
        /// </summary>
        public static string ShareModalCopyButtonText {
            get {
                return ResourceManager.GetString("ShareModalCopyButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این صفحه را با دوستان خود به اشتراک بگذارید!.
        /// </summary>
        public static string ShareModalText {
            get {
                return ResourceManager.GetString("ShareModalText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اشتراک گزاری.
        /// </summary>
        public static string ShareModalTitle {
            get {
                return ResourceManager.GetString("ShareModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایشه همه.
        /// </summary>
        public static string ShowMoreButton {
            get {
                return ResourceManager.GetString("ShowMoreButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورود به حساب کاربری.
        /// </summary>
        public static string SignInFormButtonTitle {
            get {
                return ResourceManager.GetString("SignInFormButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خوشحالم که دوباره می بینیمت
        ///لطفا وارد حساب کاربری خود شوید.
        /// </summary>
        public static string SignInPageDescription {
            get {
                return ResourceManager.GetString("SignInPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خوش برگشتی.
        /// </summary>
        public static string SignInPageHeadingTitle {
            get {
                return ResourceManager.GetString("SignInPageHeadingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورود به سایت.
        /// </summary>
        public static string SignInPageTitle {
            get {
                return ResourceManager.GetString("SignInPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت نام.
        /// </summary>
        public static string SignUpFormButtonTitle {
            get {
                return ResourceManager.GetString("SignUpFormButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای ایجاد حساب کاربری و شروع، اطلاعات خود را در زیر وارد کنید.
        /// </summary>
        public static string SignUpPageDescription {
            get {
                return ResourceManager.GetString("SignUpPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خوش آمدی.
        /// </summary>
        public static string SignUpPageHeadingTitle {
            get {
                return ResourceManager.GetString("SignUpPageHeadingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت نام در سایت.
        /// </summary>
        public static string SignUpPageTitle {
            get {
                return ResourceManager.GetString("SignUpPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسیر یکتا (انگلیسی).
        /// </summary>
        public static string Slug {
            get {
                return ResourceManager.GetString("Slug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شبکه های اجتماعی.
        /// </summary>
        public static string SocialMediaContactSection {
            get {
                return ResourceManager.GetString("SocialMediaContactSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس شبکه های اجتماعی.
        /// </summary>
        public static string SocialMedias {
            get {
                return ResourceManager.GetString("SocialMedias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ترتیب.
        /// </summary>
        public static string Sort {
            get {
                return ResourceManager.GetString("Sort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to روزهای اقامت.
        /// </summary>
        public static string StayDays {
            get {
                return ResourceManager.GetString("StayDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موضوع.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زیرعنوان.
        /// </summary>
        public static string SubTitle {
            get {
                return ResourceManager.GetString("SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خلاصه.
        /// </summary>
        public static string Summary {
            get {
                return ResourceManager.GetString("Summary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برچسب.
        /// </summary>
        public static string Tag {
            get {
                return ResourceManager.GetString("Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تلگرام.
        /// </summary>
        public static string Telegram {
            get {
                return ResourceManager.GetString("Telegram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to به طور موقت تغییر مسیر داده شد 307.
        /// </summary>
        public static string TemporaryRedirect307 {
            get {
                return ResourceManager.GetString("TemporaryRedirect307", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متن.
        /// </summary>
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امروز.
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برترین ها.
        /// </summary>
        public static string TopScoreJobs {
            get {
                return ResourceManager.GetString("TopScoreJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دوران نقاهت.
        /// </summary>
        public static string TotalStay {
            get {
                return ResourceManager.GetString("TotalStay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تراکنش.
        /// </summary>
        public static string Transaction {
            get {
                return ResourceManager.GetString("Transaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع تراکنش.
        /// </summary>
        public static string TransactionType {
            get {
                return ResourceManager.GetString("TransactionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بیمار.
        /// </summary>
        public static string Treatment {
            get {
                return ResourceManager.GetString("Treatment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توییتر.
        /// </summary>
        public static string Twitter {
            get {
                return ResourceManager.GetString("Twitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع.
        /// </summary>
        public static string Type {
            get {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to به دلایل امنیتی غیرقابل دسترسی است 451.
        /// </summary>
        public static string UnavailableForLegalReasons451 {
            get {
                return ResourceManager.GetString("UnavailableForLegalReasons451", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ بروزرسانی.
        /// </summary>
        public static string UpdateDate {
            get {
                return ResourceManager.GetString("UpdateDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه‌ کاربری.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقش کاربر.
        /// </summary>
        public static string UserRole {
            get {
                return ResourceManager.GetString("UserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اعتبار از تاریخ.
        /// </summary>
        public static string ValidDateFrom {
            get {
                return ResourceManager.GetString("ValidDateFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اعتبار تا تاریخ.
        /// </summary>
        public static string ValidDateTo {
            get {
                return ResourceManager.GetString("ValidDateTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تأیید حساب.
        /// </summary>
        public static string VerificationEmailFormButtonTitle {
            get {
                return ResourceManager.GetString("VerificationEmailFormButtonTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفاً با وارد کردن کد تأیید حساب خود را تأیید کنید.
        /// </summary>
        public static string VerificationEmailPageDescription {
            get {
                return ResourceManager.GetString("VerificationEmailPageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب کاربری خود را تأیید کنید.
        /// </summary>
        public static string VerificationEmailPageHeadingTitle {
            get {
                return ResourceManager.GetString("VerificationEmailPageHeadingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کد ارسال شده به ایمیل خود را وارد کنید تا حساب کاربری شما فعال شود.
        /// </summary>
        public static string VerificationEmailPageNote {
            get {
                return ResourceManager.GetString("VerificationEmailPageNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تأیید حساب کاربری.
        /// </summary>
        public static string VerificationEmailPageTitle {
            get {
                return ResourceManager.GetString("VerificationEmailPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ویدئو.
        /// </summary>
        public static string Video {
            get {
                return ResourceManager.GetString("Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بازدید.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کیف پول.
        /// </summary>
        public static string Wallet {
            get {
                return ResourceManager.GetString("Wallet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to واتساپ.
        /// </summary>
        public static string Whatsapp {
            get {
                return ResourceManager.GetString("Whatsapp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سال.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
    }
}
